// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/inventory-layouts/CardGrid.tsx": () => import("../components/mockups/inventory-layouts/CardGrid.tsx"),
  "./components/mockups/inventory-layouts/CompactDashboard.tsx": () => import("../components/mockups/inventory-layouts/CompactDashboard.tsx"),
  "./components/mockups/inventory-layouts/SplitPanel.tsx": () => import("../components/mockups/inventory-layouts/SplitPanel.tsx")
};
